### ISSUE TITLE
Add a voice technique page

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/dictation-toolbox.org#1]
@alexboche's post in the Caster gitter would be a start:

I have had some pretty bad voice strain in the past which started almost right away when I started using voice recognition to control my computer. Here are a few things I found helpful. I can't say I totally understand what causes the problem to get worse and better,but there are definitely some things you can do. there were times where I felt like I could barely do 10 minutes without straining my voice. Oftentimes now I can go all day without problems,but not always

drink a lot of water especially when you wake up. you don't want your throat to feel dry. sometimes it takes a while for the water to absorb
you can try doing a vocal warm-up before you start talking to your computer especially when you wake up. My vocal warm-up is: some yawn sighs followed by me saying "meum" repeatedly. when saying "meum" I tried to keep my voice as resonant as possible, vibrating my mouth and nose (also called the vocal mask) and not using any effort in the throat. I then practice just talking using the same resonance and pitch as when I'm doing the "meum" exercise; of course it's okay to vary or pitch a bit. I try to keep up this stuff as I talk in real life and use voice recognition. Another exercise uses straws though I haven't found this one is effective

*I also try to hit my optimal pitch (optimal pitch just means the pitch that makes your voice most resonant for me it's about B2/C3, I'm an adult male; you can try to figure this out yourself, it's not an exact science just a general sense of what pitch feels the brightest/most resonant when you talk at it). I actually tried to raise my voice a bit higher in general not just for voice recognition because my voice therapist recommended that. (I was talking more around E2 so I had to increase almost half an octave to my optimal pitch). For a while, I had a command that played my optimal pitch note for me.

try talk to your computer in the same relaxed way you talk in real life.

I found, repetitive single command utterances are often the most straining. try to string together commands
voiceless consonants put the least strain on your voice since they don't use your vocal cords. I use "sh" to click and "s" to double-click in Dragon. to set this up just type in "shsh" (the spelling sh should work to, not sure why I spell it shsh) to a full text control application, then highlight it and say "train that" . this will train the command without adding it to your vocabulary (weird). Then assign "shsh" to a command that clicks some people used noise recognition: I think David zurow has some stuff; talon has some stuff like a popping noise and hiss. in the long run I could imagine the popping causing some TMJ problems or something)
be careful with your voiceoutside of voice recognition. since I started using voice recognition, I stopped going to loud bars/clubs and avoid hard liquor (which can be rough on your throat.) I also stopped shouting to my family members from upstairs.

I found that some sucking candies like lifesavers were useful for lubrication when my throat felt really dry.

if your voice/throat gets really bad, you might have to take a few days or even a week off voice recognition. then start to get back into it gradually and build up some endurance over time; don't just jump in from nothing into doing it five hours a day. when you are using it yeah take breaks and use a break reminder/enforcer if you can't enforce them yourself (pcwork break is one I know, not great; rsiguard I think is another).
The Alexander technique is another thing I've heard of but I have never tried that
if the problem persists, consider seeing a professional voice therapist (in the US this is typically called a speech language pathologist. you might have to be referred by your doctor or a doctor specializing in otolaryngology aka ear nose and throat)
sorry for the novel. hope some of this is helpful

**Comment by kendonB** [comment]
more gitter:
SwellGuy Jul 16 16:25
I have had problems with my voice too. They seem to have improved.
For me saying kick or click was causing a lot of strain. Moving to a touch screen was the single biggest help for me. It alleviated a ton of mouse usage causing arm problems too.
Coffee as much as I love it dries out my throat. I still drink it sometimes but if I'm having a bad day I avoid it.
I still have a terrible time with dragon getting into fits of not understanding me and repeating myself a dozen times. I don't know what else to do about it. I have a good mic with USB sound card and have the accuracy slider set to Max - I followed the know brainer instructions for dragon configuration. Maybe it has something to do with lots of active processes or something. Usually restarting my computer gives me a few good hours. Outlook seems to cause hangs and delays as well - I think dragon must be calling accessibility apis that are slow with too many screen objects since it's supported for select and say. Sometimes normal mode ceases to work and i have to use commands to type in outlook. Would be curious if others have advice on this issue. Dragon is a pleasure to use when it works but gets me cursing daily.
Silent (acid) reflux at night was contributing. Sleeping with my mattress on an incline helped as did not eating 3 hours before bed.

**Comment by mirober** [comment]
Done! Thanks

https://dictation-toolbox.github.io/dictation-toolbox.org/voice%20strain.html
